kymatio/kymatio

- examples/1d/plot_classif.py
To get the number of classes in `plot_classif.py`, we need to
transfer the Tensor to CPU memory before calling `unique`, since
it is not implemented for CUDA Tensors.
> BUG Fix error when calling `unique` on CUDA tensor

- kymatio/caching.py
- kymatio/datasets.py
- kymatio/scattering1d/backend/__init__.py
- kymatio/scattering2d/backend/__init__.py
- kymatio/scattering2d/tests/test_scattering2d.py
- kymatio/scattering3d/backend/__init__.py
Before, we had `SCATTERING_*` variables. Now we have `KYMATIO_*` variables. This PR also changes the names of some files (config files and caching/datasets directories) to say `kymatio` instead of `scattering`.
> MAINT Replace some environment variables and config file names

- setup.py
In #171, I wrote a parser that strips out the badges of the PyPI readme. But I forgot to split by line before that.
This commit bugfixes the previous PR in that it correctly strips out the badges and avoids the unwanted carriage returns after every word.
Closes #169
> [BUG] avoid spurious carriage return in PyPI readme

- kymatio/__init__.py
Closes #182
from .version import version as __version__ in __init__.py allows kymatio.__version__ to be equal to kymatio.version.version
This is compliant with PEP 396
I'm taking the opportunity of this PR to reorder 1D, 2D, and 3D imports
> MAINT define __version__

- setup.py
The name of the library is Kymatio while the name of the module is kymatio
That said, virtually all other libraries which have fancy capitalization in their names use the lowercase capitalization in their PyPI and conda distributions.
ex: SciPy is `scipy`, NumPy is `numpy`, TensorFlow is `tensorflow`, PyTorch is `torch`, Pandas is `pandas`, BLAS is `blas`, IPython is `ipython`, etc. The list goes on.
The only exceptions I'm aware of are Keras (`Keras`), Theano (`Theano`), PySoundFile (`PySoundFile`), and Sphinx (`Sphinx`).
The reason why I'm proposing this change is that otherwise it might lead to users trying to do `import Kymatio` whereas the correct capitalization is `import kymatio`. So it's good to hint at the correct capitalization in the PyPI distribution.
> MAINT set DISTNAME to lowercase kymatio

- kymatio/scattering2d/filter_bank.py
closes #175
the function filter_bank_real no longer exists
filter_bank does what filter_bank_real used to do and does not cache the filters
+ some docstring and PEP8 improvements
> FIX disable caching of 2-d filter banks

- examples/1d/compute_speed.py
- examples/1d/plot_classif.py
- examples/1d/plot_real_signal.py
- examples/1d/plot_synthetic.py
- kymatio/scattering1d/scattering1d.py
- kymatio/scattering1d/tests/test_scattering1d.py
Previously, inputs to the scattering transform had to have a
channel axis that was always of dimension one. This is no longer
the case. An input of shape `(B, T)` is converted to a scattering
output of shape `(B, C, T1)`, where `C` is the number of scattering
coefficients and `T1` is the subsampled length of the signal.
Fixes #213.
> ENH Make 1D input shapes `(B, T)`, not `(B, 1, T)`

- kymatio/scattering1d/scattering1d.py
- kymatio/scattering1d/tests/test_scattering1d.py
This addresses #218, making the transforms accept any shape input, as long as the last `d` dimensions line up with the shape for which the transform is defined, where `d` is the dimension of the transform.
> ENH Make transforms batch shape agnostic

- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
This will make `Scattering3D` behave more like the 1D/2D code and have `cpu()` and `cuda()` methods that make it accept CPU or GPU tensors depending on the state. Right now, this only changes a flag, but it might be useful later to optimize the GPU calculations.
Fixes #220.
> API Create CPU/CUDA interface for 3D

- examples/3d/scattering3d_qm7.py
- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
This makes the interface consistent with the 1D and 2D transforms,
which both have `max_order`.
Fixes #196.
> API Change 3D flag from `order_2` to `max_order`

- README.md
Fixes #236 
Other minor changes to the README
* break down "What makes Kymatio different" into subsections
* rename "important links" to "online resources" and include in a documentation section.
* integrate the "important note about large images" into "GPU acceleration"
> [DOC] reorganize README [ci skip]

- kymatio/scattering1d/scattering1d.py
- kymatio/scattering3d/scattering3d.py
These removes the annoying `DeprecationWarning: invalid escape sequence \s` that pop up when we put LaTeX formulas in the docstrings. The solution we've opted for so far is to double escape these (so `\s` becomes `\\s`). Another option is to use raw string literals for the docstrings.
> FIX Address invalid escape warnings

- kymatio/scattering1d/scattering1d.py
This way, the only required parameters are `J` and `shape`, just like in
2D and 3D.
Closes #245.
> ENH Make `Q = 1` the default in 1D

- kymatio/scattering1d/tests/test_scattering1d.py
- kymatio/scattering2d/tests/test_scattering2d.py
Since it only supports CUDA tensors, we need to cast the tensors and
transform objects before calling `forward`.
Fixes #253.
> TST Fix tests for skcuda backend

- kymatio/scattering1d/scattering1d.py
Specifically, don't allocate a tensor of the same size as for
`max_order = 2`.
Fixes #292.
> FIX Make `max_order = 1` work properly for 1D

- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/tests/test_filters.py
- kymatio/scattering1d/tests/test_scattering1d.py
- kymatio/scattering1d/tests/test_utils.py
- kymatio/scattering1d/utils.py
Add tests to cover more cases in the code (mainly catching errors and warning) and remove code that is never executed (such as `pass` statements).
Needs to be merged on top of #298.
> TST Improve test coverage in 1D

- kymatio/scattering3d/tests/test_scattering3d.py
Specifically, `linfnorm` and `rerror`.
> ENH Remove unused functions in 3D tests

- .travis.yml
- tools/travis_install.sh
For compatibility reasons, we also run the test suite in a bare Python environment, installing all the packages using `pip`. This is done in addition to the existing tests, which are run using the `conda` package manager.
Addresses #319.
> TST+WIP Make Travis test a bare `pip` environment

- README.md
- doc/source/userguide.rst
Text nodes of the form `[text]` apparently get treated like BibTeX references,
so if it can't find that reference in the bibliography, it yells at you.
Documented here:
https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/141
Fixes #347.
> DOC Fix link formatting in user's guide

- .travis.yml
- CONTRIBUTORS.md
- Jenkinsfile
- setup.py
- tools/Dockerfile
This enables us to test the GPU functionality of the package as part of the continuous integration done with each PR and push to branches on the main repo. The test suite is currently run for both the torch and skcuda backends.
Since the Jenkins server is only accessible from within Flatiron, only the status (i.e., pending/failure/success) of the test will be visible publicly. If you would like more detailed information, you'll have to ask me or someone else who works here.
Fixes #267.
> TST Set up Jenkins CI at Flatiron

- kymatio/scattering2d/backend/backend_skcuda.py
- kymatio/scattering2d/backend/backend_torch.py
- kymatio/scattering2d/scattering2d.py
- kymatio/scattering2d/tests/test_scattering2d.py
> FIX bug on the input sizes

- examples/2d/plot_filters.py
This PR fixes one of the 2D examples that became outdated after PRs #345 and #320 
I can squash to one commit if you prefer, but left it separated for now in case you don't want the stylistic changes in the third commit.
I added `plt.show()` so that the plots will stay around for users running the example from the command line rather than an interactive session. Otherwise the figures pop up and immediately disappear when the script reaches the end.
> fix 2D example: plot_filters.py

- Jenkinsfile
The codecov uploader looks for a `coverage.xml` file in the main directory (the $WORKSPACE environment variable in the Jenkinsfile). If it can't find one, it tries to call `coverage xml` which converts the
Python coverage file `.coverage` into `coverage.xml`. For some reason, the uploader was able to do this conversion automatically before, but now (probably because `coverage` is only accessible through `python3 -m coverage` now) it fails. The fix is therefore to manually call `python3 -m coverage xml` after running the tests.
> FIX Jenkins code coverage

- doc/source/userguide.rst
> DOC Fix capitalization of `User guide`

- kymatio/scattering3d/backend/backend_skcuda.py
- kymatio/scattering3d/tests/test_scattering3d.py
The first part ensures that the skcuda backend emits the same warnings as the torch backend for non-contiguous arrays in `cdgmm`. The second part ensures that these (and other errors) are appropriately tested.
Fixes #339 and #408.
> FIX+TST Emit proper warnings in 3D backends and test for them

- kymatio/scattering2d/backend/backend_skcuda.py
- kymatio/scattering2d/backend/backend_torch.py
- kymatio/scattering2d/scattering2d.py
- kymatio/scattering2d/tests/test_scattering2d.py
- kymatio/scattering2d/utils.py
In addition to what I discussed in https://github.com/kymatio/kymatio/issues/363#issuecomment-513037055, I fixed a bug for the case `M != N`, because pytorch expects its padding sizes in the reverse order.
Hopefully fixes #363 for real.
> Fix two bugs for the max scale case (final output size of 1).

- kymatio/scattering2d/backend/torch_backend.py
- kymatio/scattering2d/tests/test_scattering2d.py
- kymatio/scattering2d/tests/test_torch_scattering2d.py
We reparametrize the tests using backend–device tuples, extend tests to increase coverage, and make some smaller cosmetic changes. Ideally, this should simplify writing the tests for the TF frontend.
> WIP Simplify and extend 2D torch tests

- kymatio/frontend/numpy_frontend.py
- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/core/scattering2d.py
- kymatio/scattering2d/frontend/__init__.py
- kymatio/scattering2d/frontend/numpy_frontend.py
- kymatio/scattering2d/tests/test_numpy_scattering2d.py
This is the PR for the NumPy back/frontends. This is up next for review, then TF. 
I tried to make some fixes, however the tests do not run. The current error I am getting is `E       TypeError: __init__() missing 2 required positional arguments: 'J' and 'shape'`, and this is occurring in the numpy_frontend abstract class. I'm not sure why its giving this error, when the torch frontend is initalized in the same way and there is no difference between the two. Perhaps this difference is due to the numpy abstract frontend subclassing off of object?
> ENH NumPy 2D Back/Frontend [3b]

- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/backend/torch_backend.py
- kymatio/scattering2d/core/scattering2d.py
- kymatio/scattering2d/tests/test_numpy_scattering2d.py
- kymatio/scattering2d/tests/test_torch_scattering2d.py
Fixes #463. To be merged before the TF frontend–backend, which is then to be rebased on top of this to avoid dealing with `squeeze`.
> REF Remove calls to `unsqeeze` and `expand_dims`

- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/backend/torch_backend.py
- kymatio/scattering2d/backend/torch_skcuda_backend.py
- kymatio/scattering2d/core/scattering2d.py
- kymatio/scattering2d/tests/test_numpy_scattering2d.py
- kymatio/scattering2d/tests/test_torch_scattering2d.py
This will simplify the TF frontend, since TF doesn't allow item assignment in `Tensor`s. As a result, we must construct list of `Tensor`s beforehand and concatenate them at the end. This implementation is slightly less efficient in NP and Torch, but seems to be the most straightforward way of implementing it in TF.
> REF Reintroduce lists of coefficients in 2D core

- kymatio/version.py
follows PEP 440 formatting
```
#
#
#
#
```
once this gets merged i will make a PR on master to advertise
> set version to 0.2.a0

- kymatio/scattering2d/frontend/__init__.py
Use import_module instead of passing in unknown globals/locals. This resolves #484 .
> MAINT no longer pass unknown globals and locals

- Jenkinsfile
- tools/Dockerfile
This includes updating the Dockerfile (upgrading the base Docker image,
installing TF-2.0 for GPU, etc.), adding a check for TF accessing the
GPU in the Jenkinsfile, and setting `TF_FORCE_GPU_ALLOW_GROWTH` to
prevent TF from allocating all the GPU memory for itself.
> TST Update Jenkins for TF-2.0 compatibility

- tools/travis_install.sh
This way, it'll fail the test early if there are errors installing.
> TST Add `set -e` to Travis script

- Jenkinsfile
Since we no longer depend on the KYMATIO_BACKEND environment variable,
all the tests are performed in the torch stage, so we remove the skcuda
stage and rename the torch stage to main.
> TST Remove skcuda stage in Jenkins

- kymatio/scattering3d/backend/torch_backend.py
- kymatio/scattering3d/backend/torch_skcuda_backend.py
- kymatio/scattering3d/core/scattering3d.py
- kymatio/scattering3d/frontend/base_frontend.py
- kymatio/scattering3d/frontend/torch_frontend.py
- kymatio/scattering3d/tests/test_torch_scattering3d.py
Two tests were removed. Attention should be paid attention to the final torch test (test_scattering_batch_shape_agnostic). This test had the assumption that the output shape was of length 5, not sure if this is the case for the integrals output size.
@eickenberg @edouardoyallon thoughts on the final test?
> Removal of torch averaging functions

- kymatio/scattering1d/tests/test_torch_scattering1d.py
- kymatio/scattering2d/tests/test_torch_scattering2d.py
- kymatio/scattering3d/tests/test_torch_scattering3d.py
This way, we don't silently fail when the skcuda backend module has
errors in it. Fixes #518.
> TST Don't import skcuda backend inside try

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- kymatio/scattering2d/core/scattering2d.py
- kymatio/scattering2d/frontend/base_frontend.py
- kymatio/scattering2d/frontend/numpy_frontend.py
- kymatio/scattering2d/frontend/tensorflow_frontend.py
- kymatio/scattering2d/frontend/torch_frontend.py
This is a proposal for dealing with metadata in the 2D code. The idea is to not have a separate `meta` function (or `filters`), but to output the metatdata *along* with the scattering coefficients, if desired. Here, this is achieved using the `out_type` attribute. By default, it is set to `'array'`, which returns the array/tensor we normally get. If it's set to `list`, we get a list of dictionaries. The indexing of the list corresponds to that of the array output (the second dimension if the batch index is one-dimensional). Each element has a key `'coef'`, which contains the actual scattering coefficients, but also `'j'` and `'theta'`. (Probably makes sense to have an `'order'` key, among others, but this is just a proof of concept.)
As an example, we have (in the NP frontend)
```
x = …
```
> API Attempt at new meta

- doc/source/userguide.rst
- kymatio/scattering1d/frontend/base_frontend.py
Closes #411 
This fix an issue concerning the documentaiton of intput/output shape for 1D which was reported in #411
> Fix doc 1 d

- kymatio/frontend/entry.py
- kymatio/frontend/keras_frontend.py
- kymatio/frontend/numpy_frontend.py
- kymatio/frontend/tensorflow_frontend.py
- kymatio/frontend/torch_frontend.py
- kymatio/keras.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/keras_frontend.py
- kymatio/scattering2d/frontend/base_frontend.py
- kymatio/scattering2d/frontend/keras_frontend.py
This way, we can run
```
from kymatio import Scattering2D
S = Scattering2D(J=3, frontend='keras')
``
and have things work as expected. This PR also hooks the Keras frontend into the documentation template so docstrings should now be there. This last part required reworking some of the templates since the Keras frontend is a little different than the others (it doesn't have a `shape` attribute and it doesn't support non-vectorized outputs).
> REF+DOC Make Keras importable from ScatteringEntry

- README.md
For some reason, wrapping a raw HTML image in an MD hyperlink doesn't
play well with M2R. Need to do the whole thing in HTML.
> DOC Fix FI logo

- requirements_optional.txt
Right now, m2r is not compatible with Sphinx v3.
See https://github.com/miyakogi/m2r/issues/51.
> DOC Downgrade Sphinx version

- Jenkinsfile
- kymatio/scattering1d/backend/torch_skcuda_backend.py
- kymatio/scattering2d/backend/torch_skcuda_backend.py
- tools/Dockerfile
This PR gets Jenkins up and running again. There are four main contributions:
- Upgrade `pip` before calling `pip install`. This ensures that we can take advantage of the newer `manylinux2010` and `manylinux2014` wheels. The default version (v9) only installs `manylinux1` wheels and when it can't find them, tries to compile from source, which is a bad idea.
- Invoke `pip` using `python3 -m pip` instead of `pip3` since this is a more robust approach.
- Output version information for `pip` and the installed packages. This should help debugging in the future.
- Fixes usage of internal `cupy` components, which have moved from `cupy.utils` to `cupy._utils` in v8.
> TST Fix Jenkins

- .github/workflows/conda.yml
- .github/workflows/pip.yml
Adds configuration files for two workflows: one for pip install and one for conda install. Ideally, it should just pop up as a check in the PR, but we'll see.
> TST Try GH actions for pip tests

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/frontend/base_frontend.py
Currently, the signal length is denoted by T in 1D, which is easily
confused with the averaging scale 2 ** J and inconsistent with the
notation for 2D, where the shape is given by M, N. As a result, we
change the notation to N.
Closes #656.
> MAINT Rename T → N in 1D

- .github/workflows/conda.yml
- .github/workflows/pip.yml
Extend support to Python 3.8. Rename the build jobs to distinguish pip and conda (hopefully).
Partially addresses #642.
> Update GitHub Actions CI

- kymatio/backend/numpy_backend.py
- kymatio/backend/tensorflow_backend.py
- kymatio/backend/torch_backend.py
- kymatio/backend/torch_skcuda_backend.py
- kymatio/frontend/numpy_frontend.py
- kymatio/frontend/torch_frontend.py
- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- kymatio/scattering1d/backend/torch_skcuda_backend.py
- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/backend/tensorflow_backend.py
- kymatio/scattering2d/backend/torch_backend.py
- kymatio/scattering2d/backend/torch_skcuda_backend.py
- kymatio/scattering3d/backend/numpy_backend.py
- kymatio/scattering3d/backend/tensorflow_backend.py
- kymatio/scattering3d/backend/torch_backend.py
- kymatio/scattering3d/backend/torch_skcuda_backend.py
- tests/general/test_torch_backend.py
- tests/scattering1d/test_numpy_backend_1d.py
- tests/scattering1d/test_tensorflow_backend_1d.py
- tests/scattering1d/test_torch_backend_1d.py
- tests/scattering1d/test_torch_scattering1d.py
- tests/scattering2d/test_torch_backend_2d.py
This PR is in progress. All the tests currently do not run. 
Refactors the named tuple convention out of the 1d.
> API Backend refactor

- tests/scattering2d/test_tensorflow_backend_2d.py
The implementation used by TF to calculate the FFT is not very
accurate, so we need to relax the tolerance a little to eliminate
spurious test failures.
Fix #663.
> TST Relax tolerance in 2D TF FFT unit test

- examples/2d/plot_scattering_disk.py
Add second-order coefficients visualisation for plot_scattering_disk example and display same output as in Bruna and Mallat's paper
> Add second-order coefficients visualisation

- .github/workflows/docs.yml
- doc/source/conf.py
- requirements_optional.txt
- tools/push_doc.sh
Add a GitHub Actions workflow for generating the docs and pushing them to GitHub pages. So far only for `master`.
Depends on #687.
> Update docs (episode II)

- kymatio/version.py
PEP440 compliant
follows sklearn convention https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/__init__.py#L26
> set version to 0.3.dev0 in dev branch

- tools/Dockerfile
This adds a custom build of pytorch 1.7.1 for the older GPUs on the jenkins machine.
I also pinned torchvision 0.8.2 to match the torch version.
Tests seem to be passing.
If you'd prefer we could make this a separate test and run both torch 1.2 and 1.7 separately.
> Update jenkins environment with torch 1.7.1

- tools/Dockerfile
We've now added v100 GPUs to jenkins, so the custom tensorflow build is no longer necessary.  (Alternatively we could keep it and add support for the new GPUs so we can run on both, but probably there's not much point.)
> Remove custom tensorflow build

- examples/2d/plot_sklearn.py
Dear Esteemed Colleagues,
please accept my State of the Art (SOTA) result on the "Kymatio Sklearn Digit Recognition Benchmark" Benchmark.
Love,
ScatteringSepoy
-------------------------------------------------------
To be much less trolly, this PR removes a warning thrown by sklearn about a lack of convergence, while keeping the same runtime and improving accuracy by about 1.5 percent. 
This goes a small way of solving #817 .
> DOC Remove warning from sklearn example. 

- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/utils.py
- tests/scattering1d/test_filters_scattering1d.py
Backwards compatible
No new functionality
Note! Test function was modified to use a value of alpha=5.
Removed default value for alpha parameter everywhere in filter_bank.py except factory function (scattering_filter_factory). This way the value of alpha is set once, avoiding a possible override of this value by the default.
> Removed redundant default value for alpha

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
Fixes #836
One kwarg less from `scattering1d` in base_frontend.py`
Fewer LOCs, fewer repetitions
> remove `size_scattering` kwarg from `scattering1d`

- examples/1d/plot_filters.py
- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/utils.py
- tests/scattering1d/test_numpy_scattering1d.py
Fixes https://github.com/kymatio/kymatio/issues/840 
`scattering_filter_factory` should not return `t_max_phi`
* Net reduction in LOC count
* Simplification of the `scattering1d/filter_bank` module
* Faster `Scattering1D` constructor
* no more `criterion_amplitude` being passed to `scattering_filter_factory`
* no more `compute_minimum_support_to_pad`
* Backwards compatible as far as frontends are concerned
The calls to scattering_filter_factory will require a rebase from https://github.com/kymatio/kymatio/pull/833
> MAINT decouple `scattering_filter_factory` from `ScatteringBase1D.build`

- kymatio/scattering1d/filter_bank.py
> MAINT simplify `compute_params_filterbank`, remove `_move_one_dyadic_step`

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
Fixes #852
a lighter and better focused version of #855
unfortunately the same thing cannot be done in 2D right now because the logic is quite different: `self.pad` is a backend function which is being defined at `build` time and takes `self.shape` as input. It also depends upon a parameter `pre_pad`. It's almost like an object inside the `Scattering2D` object.
Next step for me is to remove `pad_left` and friends and perform padding/unpadding outside of scattering. We've discussed a plan with @MuawizChaudhary for that. (in the spirit of #735 )
> avoid passing `log2_T`, `pad`, `unpad` to 1D core

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/keras_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- tests/scattering1d/test_torch_scattering1d.py
Fix #843 
(a second attempt after some productive discussions during review of #844)
This is a planned change for v0.3
The default behavior is still `out_type="array"` (`vectorize=True`)
We introduce `out_type="dict"` to replicate the behavior of `out_type="array", vectorize=False`
A net reduction in code size thanks to utility methods `_check_runtime_args()` and `_check_input()` in `ScatteringBase1D`
Written on top of #860. I suggest we look at #860 first
Tests pass locally
Note that vectorize is still documented in the base frontend. I'll take care of updating these docs after code review.
> Remove vectorize + write frontend-agnostic runtime checks

- examples/3d/scattering3d_qm7_torch.py
The 3D example on dev fails an import due to the fact that we now use a class structure for the backend. This PR fixes this by importing instead the backend and calling compute integrals. 
[Currently in the process of running the full example on a google colab.](https://colab.research.google.com/drive/1FzK481GSptZijQrmjRuJV9GNJcdtgyku?usp=sharing) 
This goes a small way of solving #817 .
> DOC Fix 3d example failing import

- kymatio/scattering3d/utils.py
Back in the good old days, before I existed, [Kymatio reimplemented various calls](https://github.com/kymatio/kymatio/commit/12b082fca0e3fdc88bee3220c9e867a29fee5d11#diff-144c72d86c0312177446796e4be3836116b58a5e9169cdea6254a24ab3243134R236) that a `nn.module` had. These included `.cpu`,`cuda`, and were often implemented using a `_apply` call.
A reviewer of our JMLR submission kindly noted that we could just inherit from a `nn.module` instead of reimplementing all those calls. 
This `_apply_filters` tucked and hidden away in the 3d utils code is the last remaining vestige of this old way of doing things.
> MAINT removed useless apply function

- examples/1d/plot_real_signal.py
- examples/1d/plot_synthetic.py
This PR fixes plots in the 1d code from overlapping one another. 
From `plot_real_signal.py`.
From `plot_synthetic.py`.
This goes a small way of solving #817
> DOC Use tight_layout to prevent plot axes from overlapping one another

- examples/1d/reconstruct_torch.py
This pull request fixes an example from erroring out due to not detaching tensors from the computational graph before converting to numpy. 
This goes a small way of solving #817
> DOC fix reconstruct_torch.py example by calling detach

- examples/1d/plot_filters.py
- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/frontend/torch_frontend.py
- tests/scattering1d/test_torch_scattering1d.py
as discussed in #775
done in duet with @MuawizChaudhary 
ready for code review
i still need to update some docs
triaged for v0.3
once this PR passes code review, i'll work on 2D and 3D
> Make `Scattering1D` compatible with TF>=2.5

- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/utils.py
no more `detail` kwarg
fixes #838
came up in conversation with @janden and @MuawizChaudhary : https://github.com/kymatio/kymatio/issues/838#issuecomment-1151084298
> `precompute_size_scattering` now returns a tuple

- kymatio/scattering3d/backend/numpy_backend.py
- tests/scattering3d/test_numpy_scattering3d.py
- tests/scattering3d/test_tensorflow_scattering3d.py
- tests/scattering3d/test_torch_scattering3d.py
This PR resolves issue #811 and adds a few tests confirming the fix.
> MAINT HarmonicScattering3D now outputs real coefficients in Numpy. 

- kymatio/frontend/entry.py
- tests/scattering1d/test_utils_scattering1d.py
- tests/scattering2d/test_frontend_scattering2d.py
- tests/scattering3d/test_torch_scattering3d.py
This PR resolves #868, making Numpy the default frontend like we said we would.
> MAINT make NumPy the default frontend

- benchmarks/benchmarks/numpy_benchmark/scattering1d.py
- benchmarks/benchmarks/numpy_benchmark/scattering2d.py
- benchmarks/benchmarks/torch_benchmark/scattering1d.py
- benchmarks/benchmarks/torch_benchmark/scattering2d.py
- benchmarks/benchmarks/torch_benchmark/scattering3d.py
This Pull Request add's some style changes and removes some unneeded cuda synchronization. 
I wanted to add some documentation, but turns out y'all already added documentation during the 2021 sprint. 
I think all we need to do in terms of ASV related stuff is figure out how to integrate it into our continuous integration stack ;P
> MAINT, STY Various ASV maintenance, style changes. 

- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/utils.py
- tests/scattering1d/test_keras_scattering1d.py
- tests/scattering1d/test_numpy_scattering1d.py
- tests/scattering1d/test_tensorflow_scattering1d.py
- tests/scattering1d/test_torch_scattering1d.py
Fix https://github.com/kymatio/kymatio/issues/853
This PR makes it flexible for users to specify the number of wavelets per octave at the first and second order scattering. Both cases are working:
- Set `Q` as an integer: `Q = Q1`. In this case, we use `Q1` wavelets per octave at the first order and that for the second order defaults to one. 
- Set `Q` as a tuple: `Q = (Q1, Q2)`, where users can specify both `Q1` and `Q2` according to their needs.
>  Make `Q2` customizable

- kymatio/scattering2d/core/scattering2d.py
- kymatio/scattering2d/filter_bank.py
- kymatio/scattering2d/frontend/torch_frontend.py
> MAINT make `Scattering2D` compatible with TF>=2.5

- kymatio/frontend/base_frontend.py
- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/base_frontend.py
Fixes #869 by @MuawizChaudhary 
don't mind the title of the branch: `oversampling` is not becoming immutable.
also don't mind the title of the commit: `_check_filterbanks` belongs in `ScatteringBase`, not `ScatteringBase1D`
> move core 1D asserts to `_check_filterbanks` in `ScatteringBase`

- kymatio/scattering1d/frontend/base_frontend.py
- tests/scattering1d/test_torch_scattering1d.py
in `check_runtime_args`
and write `test_check_runtime_args`
> check `oversampling` in 1D

- kymatio/scattering2d/frontend/base_frontend.py
- kymatio/scattering2d/frontend/numpy_frontend.py
- kymatio/scattering2d/frontend/tensorflow_frontend.py
- kymatio/scattering2d/frontend/torch_frontend.py
- tests/scattering2d/test_torch_scattering2d.py
2D equivalent of #863 
triaged for v0.3
> Deprecate `self.N` in 2D

- examples/1d/plot_classif_torch.py
- examples/1d/reconstruct_torch.py
- examples/2d/cifar_resnet_torch.py
- examples/2d/cifar_small_sample.py
- examples/2d/cifar_torch.py
- examples/2d/long_mnist_classify_torch.py
- examples/3d/scattering3d_qm7_torch.py
This PR enables `to(device)` semantics for the pytorch examples. 
This resolves issue #824 .
> DOC Enable `.to(device)` semantics for pytorch examples

- kymatio/scattering3d/backend/torch_skcuda_backend.py
- tests/scattering3d/test_torch_scattering3d.py
This pull request redefines cdgmm3d to call cdgmm in torch skcuda backend. 
I'm also using this as a proxy for testing the torch_skcuda 3d backend.
> MAINT redefine cdgmm3d to call cdgmm in torch skcuda backend

- tests/scattering2d/test_tensorflow_backend_2d.py
This is a bit flaky, so let's fix the seed here.
Should probably be doing this more consistently across the tests, but that's another discussion.
> TST Add seed to 2D FFT test in TF

- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- kymatio/scattering2d/core/scattering2d.py
- tests/scattering1d/test_torch_scattering1d.py
Fix #875, Fix #895
as discussed in today's Kymatio meeting
NB: these changes must be in the release notes.
> FIX include 'n' field in 1D/2D list + remove singleton dimension in 1D dict

- kymatio/backend/numpy_backend.py
- kymatio/backend/tensorflow_backend.py
- kymatio/backend/torch_backend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- tests/general/test_numpy_backend.py
- tests/general/test_tensorflow_backend.py
- tests/general/test_torch_backend.py
Co-authored-by: Vincent Lostanlen [vincent.lostanlen@ls2n.fr](mailto:vincent.lostanlen@ls2n.fr)
* backend shape methods
* reshape_input, reshape_output in backends
* try to call reshape_output only once [ci skip]
* simplify PR, figure out "dict" as special case
* spaces around operator [ci skip]
* bugfix prev commit (concatenate dim in NP backend)
* manage multiple inheritance
move the NotImplementedError's of scattering to 2D and 3D 's base frontends
* implement scattering(self, x) in 1D base frontend
* shape(x, signal_dim) in backends
* bugfix previous commit
* Revert "bugfix previous commit"
This reverts commit de46c9efeab7ca01c2f8a74cbf8f3202148ab1b1.
* Revert "shape(x, signal_dim) in backends"
This reverts commit 937b87cf1e5287ec6b83df0eccd8b5b58d3d3728.
* add empty line in …
> `reshape_input`, `reshape_output` (#871)

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
dup of #879 but geared towards main this time
segue of https://github.com/kymatio/kymatio/pull/877, and moves further in the direction of https://github.com/kymatio/kymatio/pull/855 which closed https://github.com/kymatio/kymatio/issues/852
remove pad from core scattering1d
backwards compatible. opens the door towards custom padding in 1d (https://github.com/kymatio/kymatio/issues/859)
no additional tests
contributes to https://github.com/kymatio/kymatio/issues/735
> MAINT remove pad from core scattering1d

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/base_frontend.py
- tests/scattering1d/test_numpy_scattering1d.py
- tests/scattering1d/test_torch_scattering1d.py
dup of #880 except geared at main branch
Fourth item in a streak, after #871, #877, #879. This concludes the decoupling between core scattering versus pre-processing routines (type checks, reshaping, padding) as well as post-processing routines (reshaping again, padding, and formatting to `out_type`).
The LOC impact is more or less neutral, but the number of input arguments to `core/scattering1d` is significantly reduced:
```python
def scattering1d(U_0, backend, psi1, psi2, phi, oversampling, max_order, average=True):
```
Compare with current master branch:
```python
def scattering1d(x, pad, unpad, backend, J, psi1, psi2, phi, pad_left=0,
pad_right=0, ind_start=None, ind_end=None, oversampling=0,
max_order=2, average=True, size_scattering=(0, 0, 0),
vectorize=False, out_type='array'):
``` …
> ENH `core/scattering1d` now returns a generator

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/base_frontend.py
closes #920 
fewer input arguments to core scattering
fewer LOCs
backwards compatible
the `scattering1d` prototype is a one-liner now ! :)
a more ambitious change would have been to store `filters` as an attribute of the Scattering1D object and expose `phi_f` and friends as read-only properties. and indeed this is what i plan to do in JTFS
but it's equivalent from a usability standpoint (at least so long as we restrict Scattering1D to one or two orders) so i don't see a compelling reason to do it now.
> MAINT simpler 1d prototype

- kymatio/scattering1d/filter_bank.py
- tests/scattering1d/test_filters_scattering1d.py
For JTFS
may also serve #645 if there's interest in supporting complex-input signals in the future
very small PR. most of the interface for this was made possible by the `anden_generator` #915
no extra kwarg to the 1D factory :)
thanks to @cyrusvahidi and @MuawizChaudhary who had a first working solution for this back in May
will document this after code review
> ENH Spinned wavelets

- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/jax_frontend.py
- kymatio/scattering1d/frontend/keras_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- tests/scattering1d/test_correctness.py
closes https://github.com/kymatio/kymatio/issues/917
An oversight from https://github.com/kymatio/kymatio/pull/897 which closed https://github.com/kymatio/kymatio/issues/885. Many thanks to @cyrusvahidi for finding it and bringing it up.
Turns out, we have forgotten one important element: switch to the average=None by default! This causes DeprecationWarning in current user code even when they don't pass average. Worse, passing T=0 does not work because it clashes with the implicit average=True.
>  FIX (v0.3.X backport) set `average=None` in Scattering1D frontends

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/core/timefrequency_scattering.py
- tests/scattering1d/test_timefrequency_scattering.py
first step of the JTFS algorithm
Prototype:
```python
scattering1d_widthfirst(U_0, backend, filters, oversampling, average_local)
```
yields: U0, S1 (concatenated), Y2 (concatened) if average_local is True
yields: U0, U1 (per n1), Y2 (concatenated) if average_local is false
same as scattering1d once #921 is merged
the unit test makes sure that depth-first and width-first versions of the time scattering algorithm lead to the same outcome
advice to code reviewers: it's worth to look at `core/scattering1d.py` and `core/timefrequency_scattering.py` modules in parallel to spot the meaningful similarities and differences
will document after CR is done and conflicts with other branches are resolved. the docstring will be very close to that of existing scattering1d (depth-first)
> ENH core width-first 1d scattering for JTFS

- kymatio/scattering1d/core/timefrequency_scattering.py
- tests/scattering1d/test_timefrequency_scattering.py
So, i made a benign mistake in #923: i implemented `average_false` as yielding `U0, U1, Y2`. 
But instead it should yield `U0, S1, Y2`. 
Indeed `S1` will be passed through frequential scattering to yield `U2_phi_psi = | S1 * psi_fr |` (conv over n1, no spin)
This simplifies the logic: U1 is always averaged into S1, no matter what is the value of `average_local`. I have rewritten the tests against the depth-first implementation
> FIX JTFS `average_local=False` in `scattering1d_widthfirst`

- kymatio/scattering1d/frontend/base_frontend.py
- tests/scattering1d/test_torch_scattering1d.py
Triggers and fixes a bug in `oversampling>0` (non-default), introduced by #937 a few days ago.
> FIX `oversampling>0` in `ScatteringBase1D.scattering`

- kymatio/scattering1d/core/timefrequency_scattering.py
- tests/scattering1d/test_timefrequency_scattering.py
#945's frequential sibling
while writing this i found a metadata bug in `frequency_scattering` (#935), i.e. that we were returning `j_fr` and `n_fr` as integers instead of 1-tuples. This was unnecessarily inconsistent with first-order time scattering. So i fixed that and updated the tests. 
This is the last element of core JTFS. When #945 and this PR will be merged, i'll be able to work on a `scattering` method for the base frontend.
> ENH JTFS `frequency_averaging`

- kymatio/scattering1d/core/timefrequency_scattering.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- tests/scattering1d/test_timefrequency_scattering.py
NumPy frontend and tests
The implementation of JTFS is now complete in NumPy for the default parameters: `out_type='array'` and `format='joint'`.
Supporting other `out_type`'s (`dict` and `list`) will require another Kymatio primitive: `backend.unpad_frequency`.
Supporting `format='time'` will require another Kymatio primitive: `backend.split`.
I am raising`NotImplementedError`'s where these primitive calls need to happen.
This PR adds some missed lines and thus reduces the test coverage. This is only temporary: test coverage will go back up once we implement `unpad_frequency` and `split` + corresponding tests.
NB. while writing this i found out a bug in `frequency_scattering` callsites (#935). `average_fr` and `oversampling` were being mixed up. This PR fixes the bug.
> ENH JTFS `TimeFrequencyScatteringBase.scattering`

- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- tests/scattering1d/test_numpy_backend_1d.py
- tests/scattering1d/test_tensorflow_backend_1d.py
- tests/scattering1d/test_torch_backend_1d.py
segue of #955 
`jtfs_average_and_format` is now fully ported to all backends
> ENH JTFS `unpad_frequency` in PyTorch and TensorFlow

- requirements_optional.txt
There was an issue a while back with sphinx-3.0 being incompatible with
the latest version of m2r (see f92b5077), but this now seems to have
been remedied.
> MAINT Unpin sphinx

- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- kymatio/scattering1d/core/timefrequency_scattering.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- tests/scattering1d/test_numpy_backend_1d.py
- tests/scattering1d/test_tensorflow_backend_1d.py
- tests/scattering1d/test_timefrequency_scattering.py
- tests/scattering1d/test_torch_backend_1d.py
This was harder than expected
See new primitive `split_frequency_axis` and additional core method `time_formatting`
The switch logic in base frontend between orders, choice of out_type, and choice of format is quite subtle now. But i think i got it right without too much code (~70 lines of base frontend for both scattering sand meta)
Ready for review, tests included
> ENH JTFS `format="time"`

- tests/scattering1d/test_tensorflow_scattering1d.py
hotfix on PR #965
fixes an issue in the `test_tensorflow_scattering1d.py` - incorrect devices had been specified for the context of the differentiability test, while not being necessary.
> hotfix on #965 tensorflow differentiability test

- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- tests/scattering1d/test_timefrequency_scattering.py
I have added the `format` kwarg for `TimeFrequencyScattering` torch and tf frontends. Upon testing, I have noticed a `RuntimeError` for `format="time"` in tensorflow
> ENH/FIX add format kwarg to TimeFrequencyScattering torch and tf frontends

- kymatio/scattering1d/core/timefrequency_scattering.py
- kymatio/scattering1d/frontend/base_frontend.py
- tests/scattering1d/test_timefrequency_scattering.py
Fixes #978
Added minimal test to check that `meta['order']` has same number of elements as Sx paths
> FIX #978 omit order0 from JTFS meta when `format="joint"`

- kymatio/scattering1d/filter_bank.py
- tests/scattering1d/test_numpy_scattering1d.py
fixes #981
tests included
it was an off-by-one error in `scattering_filter_factory`
```python
for Q_layer in Q:
psi_f = []
for xi, sigma in filterbank_fn(J, Q_layer, **filterbank_kwargs):
psi_levels = [morlet_1d(N, xi, sigma)]
j = get_max_dyadic_subsampling(xi, sigma, **filterbank_kwargs)
for level in range(1, min(previous_J, j, 1+log2_T)):
psi_level = psi_levels[0].reshape(2 ** level, -1).mean(axis=0)
psi_levels.append(psi_level)
psi_f.append({'levels': psi_levels, 'xi': xi, 'sigma': sigma, 'j': j})
max_j = max(j, max_j)
previous_J = max_j
psis_f.append(psi_f)
```
the `range(1, min(previous_J, j, 1+log2_T)` was `range(1, min(previous_J, j, log2_T)` before
> FIX include level `k2=log2_T` of `psi2_f`

- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/frontend/base_frontend.py
Fixes #984 
With @cyrusvahidi we have spotted an issue in scattering filter factory, while working on JTFS
```python
for level in range(1, min(previous_J, j, log2_T)):
psi_level = psi_levels[0].reshape(2 ** level, -1).mean(axis=0)
psi_levels.append(psi_level)
psi_f.append({'levels': psi_levels, 'xi': xi, 'sigma': sigma, 'j': j})
max_j = max(j, max_j)
```
This `.mean(axis=0)` should be a `sum` instead so as to preserve L1 norm across resolution levels.
The same problem arises in the construction of phi_levels:
```python
sigma_low = filterbank_kwargs["sigma0"] / T
phi_levels = [gauss_1d(N, sigma_low)]
for level in range(1, max(previous_J, 1+log2_T)):
phi_level = phi_levels[0].reshape(2 ** level, -1).mean(axis=0)
phi_levels.append(phi_level)
phi_f = {'levels': phi_levels, 'xi': 0, 'sigma': …
```
> FIX `_reduction=np.sum` (vs default `np.mean`) in JTFS sc filter factory

- kymatio/scattering1d/filter_bank.py
- tests/scattering1d/test_timefrequency_scattering.py
fixes #986 
The new unit test failed without the introduction of `abs(xi)` in `get_max_dyadic_subsampling`. I test that `j` is mirrored for positive and negative spinned filters. This ensures that we subsample correctly for negative spin filters.
> FIX `get_max_dyadic_subsampling` for negative `xi` in JTFS frequency filterbank construction

- kymatio/scattering1d/frontend/base_frontend.py
after v0.3 deprecation cycle
(segue of #857)
for v0.4
> remove J_pad and N from ScatteringBase1D

- tools/Dockerfile
Replace `tensorflow-gpu` package with `tensorflow` as the former has been deprecated.
> TST Fix Tensorflow pip package in Jenkins

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/core/timefrequency_scattering.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/jax_frontend.py
- kymatio/scattering1d/frontend/keras_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- kymatio/scattering1d/utils.py
- tests/scattering1d/test_keras_scattering1d.py
- tests/scattering1d/test_numpy_scattering1d.py
- tests/scattering1d/test_tensorflow_scattering1d.py
- tests/scattering1d/test_timefrequency_scattering.py
- tests/scattering1d/test_torch_scattering1d.py
- tools/Dockerfile
Fixes #937 
I have written the smallest PR possible
In a separate PR i will rewrite core 1D in terms of log2_stride instead of oversampling. But that's not necessary right now.
~~Note that stride is passed at runtime, not in the constructor. This allows to change stride between inputs without recomputing the filters.~~  actually no because this causes problem in autodiff
Should be reviewed and merged before v0.4
I will also make a PR about `stride_fr` later
> MAINT `oversampling` --> `stride`, immutable `Q` and `T`

- kymatio/jax.py
- kymatio/scattering1d/frontend/entry.py
- kymatio/sklearn.py
- tests/scattering1d/test_timefrequency_scattering.py
Following #1001 I have exported JTFS from the JAX frontend such that one can import as: from kymatio.jax import TimeFrequencyScattering
I noticed that this was also missing in sklearn.
> ENH JTFS jax module export 

- kymatio/scattering1d/frontend/base_frontend.py
segue from #1005 
in the case of JTFS, there is no backwards compatibility to be had, so we might as well remove the `_reduction` attribute from the JTFS object and pass `_reduction=np.mean` to filterbank constructors.
> MAINT remove `_reduction` from JTFS self

- examples/1d/classif_keras.py
- examples/1d/plot_classif_torch.py
- examples/1d/plot_real_signal.py
- examples/datasets.py
- requirements_optional.txt
Since `datasets.fetch_fsdd` is no longer available as part of the main `kymatio` package, we can't access it from the examples when run using `sphinx-gallery`. To solve this, we instead switch to a `librosa` example for `plot_real_signal` (`librivox3`) and use `deeplake` to download FSDD in the classification examples.
> DOC Fix 1d dataset examples

- kymatio/scattering2d/backend/tensorflow_backend.py
- tests/scattering2d/test_tensorflow_scattering2d.py
This pull request imports code over from the torch 2d pad backend primitive to tensorflow 2d pad backend primitive to solve padding issues when an element of shape `(M, N)`  is equal to `2**J`. 
This PR adds a test and closes #792.
> MAINT Tensorflow 2d padding fix

- kymatio/frontend/keras_frontend.py
- kymatio/frontend/numpy_frontend.py
- kymatio/frontend/sklearn_frontend.py
- kymatio/frontend/torch_frontend.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering2d/frontend/base_frontend.py
- kymatio/scattering3d/frontend/base_frontend.py
This pull request corrects an incorrect docstring in the sklearn documentation. I remove the use of `np.prod` in the creation of the input, and additionally add a batch dimension. 
While the documentation now correctly shows how to apply it to an input of a certain shape, the sklearn documentation example is obviously not that great.
I don't know how to build the documentation. can someone send me a tutorial on how to build it? 
This solves issue #760
> DOC correction

- .github/workflows/conda.yml
- .github/workflows/pip.yml
- tools/Dockerfile
Include `torch==2.0` for GHA as well as Jenkins (which will now install the latest version available) and update the Jenkins image to CUDA 11.7. Finally, we add testing for Python 3.11.
> TST Upgrade CI

- tests/scattering2d/test_torch_scattering2d.py
This pull request speeds up `test_gradients` by enabling `fast_mode`. Previously it took 109 seconds to run, now it takes 17 seconds. 
> fast_mode ([bool](https://docs.python.org/3/library/functions.html#bool), optional) – Fast mode for gradcheck and gradgradcheck is currently only implemented for R to R functions. If none of the inputs and outputs are complex a faster implementation of gradcheck that no longer computes the entire jacobian is run; otherwise, we fall back to the slow implementation.
Note that since our scattering takes in as input a real valued signal, and outputs a real valued signal, torch allows us to enable `fast_mode` to avoid computing additional entries of a jacobian. 
[See more here.](https://pytorch.org/docs/master/generated/torch.autograd.gradcheck.html#torch.auto …
> MAINT Speed up `test_gradients`

- examples/2d/cifar_resnet_torch.py
- examples/2d/cifar_small_sample.py
- examples/2d/cifar_torch.py
Instead of redefining the optimizer every 20 epochs during training to decrease the learning rate, I initialized it before the training loop starts along with a StepLR scheduler that will decrease the learning rate by a factor of 0.2 every 20 epochs. 
I changed this for one of the three CIFAR10 2d example scripts, and I will change the other two if everyone agrees.
This resolves issue #1021
> MAINT use lr_scheduler instead of resetting optimizer

- examples/2d/cifar_small_sample.py
Fixed 
```
AttributeError: 'ScatteringNumPy2D' object has no attribute 'to'
```
kymatio by default imports numpy backend
> Update cifar_small_sample.py to fix AttributeError

- examples/2d/cifar_small_sample.py
> Revert "Update cifar_small_sample.py to fix AttributeError"

- tests/scattering1d/test_keras_scattering1d.py
- tests/scattering3d/test_utils_scattering3d.py
This PR updates one of our tests to not use deprecated pytest code for checking if no warnings were thrown on complex input. 
Another test is also updated to convert shape inputs of type `int` to type `tuple`.
Should Solve #1045
> Fixes TypeError, Value Error in tests.
