kymatio/kymatio

- .travis.yml
sorry, should have done this from a fork!
> MAINT Add travis yml

- examples/1d/compute_speed.py
If we don't have a GPU, don't try to use a CUDA implementation.
> ENH Include CUDA check in 1D `compute_speed.py`

- doc/source/_static/bibtex.bib
- doc/source/developerguide.rst
- doc/source/userguide.rst
push to this branch to collaboratively update the docs
> WIP working on docs

- examples/2d/mnist.py
- kymatio/scattering1d/scattering1d.py
- kymatio/scattering3d/tests/test_scattering3d.py
Need to have `scattering`, not `scat`.
> MAINT Fix `scattering` in code

- examples/2d/mnist.py
Close #180 
Depreciation due to pytorch.
> FIX Removing a warning

- kymatio/scattering1d/scattering1d.py
- kymatio/scattering2d/scattering2d.py
- kymatio/scattering3d/backend/backend_torch.py
> ENH removing the unused library warnings and importing the correct one in 3D

- kymatio/scattering1d/scattering1d.py
- kymatio/scattering2d/scattering2d.py
> FIX __all__ becomes correct both for 1D and 2D

- README.md
> ENH modifying website url+adding a note for imagenet

- README.md
Sorry for creating a branch on `kymatio`, doing a quick edit in the browser. Branch will be deleted after
> DOC update readme, rephrase Imagenet comment

- doc/source/conf.py
- examples/3d/scattering3d_qm7.py
> FIX removing ignore-pattern files from sphinx' conf.py

- examples/2d/plot_filters.py
Close #106 
This finalizes the 2d filters displaying from the gallery.
> FIX fixing the 2d filters displaying from the sphinx gallery

- kymatio/version.py
Semver 2.0.0 compliant
https://semver.org/spec/v2.0.0.html
PEP 0440 compliant
https://www.python.org/dev/peps/pep-0440/
> MAINT set version to 0.1.0-dev [ci skip]

- kymatio/scattering3d/backend/__init__.py
- kymatio/scattering3d/backend/backend_skcuda.py
- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
fixes #197
I am not sure how I should be testing this because I don't understand the inner workings of test_scattering.py and how it dynamically imports a backend
> MAINT sc3d backend_skcuda.py: NotImplementedError

- doc/source/quickstart.rst
- doc/source/userguide.rst
- examples/1d/compute_speed.py
- examples/1d/plot_classif.py
- examples/1d/plot_real_signal.py
- examples/1d/plot_synthetic.py
- examples/2d/cifar.py
- examples/2d/cifar_resnet.py
- examples/2d/compute_speed.py
- examples/2d/mnist.py
- examples/2d/regularized_inverse_scattering_MNIST.py
- examples/3d/compute_speed.py
- examples/3d/scattering3d_qm7.py
- kymatio/scattering1d/scattering1d.py
- kymatio/scattering1d/tests/test_scattering1d.py
- kymatio/scattering2d/scattering2d.py
- kymatio/scattering2d/tests/test_scattering2d.py
- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
Fixes #194
This change is API-breaking and irreversible insofar as it cannot be deprecated.
It is a step in the direction of making the input shape optional.
It also improves consistency across modules.
[EDIT: fixes #202 too]
> [API] set J as first positional arg + introduce shape kwarg

- kymatio/scattering1d/scattering1d.py
also alphabetize imports, put Scattering1D class at the top of the file, fix maths in docstrings, Unicode "Andén"
> STY pycodestyle and pyflakes scattering1d.py

- examples/2d/cifar.py
- examples/2d/cifar_resnet.py
- examples/2d/mnist.py
- kymatio/scattering1d/scattering1d.py
- kymatio/scattering2d/scattering2d.py
a contribution to solving #196 in the case of 2D
more consistency between 1D and 2D
enabling the development of third-order scattering in the future
> REF bool order2 -> int max_order in Scattering2D

- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
> FIX Prevent 3D from crashing on CPU-only systems

- kymatio/scattering3d/filter_bank.py
- kymatio/scattering3d/tests/test_scattering3d.py
- kymatio/scattering3d/utils.py
> FIX Prevent `np.sqrt` from issuing erroneous warnings

- kymatio/scattering2d/scattering2d.py
- kymatio/scattering2d/tests/test_scattering2d.py
> ENH Make transforms batch shape agnostic (2D)

- CONTRIBUTING.md
- README.md
> ENH more comprehensive README

- kymatio/scattering1d/scattering1d.py
- kymatio/scattering1d/tests/test_scattering1d.py
Remove some of the fine-tuning parameters for the filters.
Fixes #227.
> API Simplify 1D constructor

- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
- kymatio/scattering3d/utils.py
This doesn't work yet. I have refactored the `standard` output so that it doesn't ravel, but my brain is in a state where I can't get the test data reshaped correctly to make the test pass.
This is the last thing we need to fix before being able to release
[EDIT by @lostanlen: closes #222]
> REF Homogenize 3d output

- examples/3d/compute_speed.py
- examples/3d/scattering3d_qm7.py
- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
Fixes #231.
[EDIT by @lostanlen: also fixes #230]
> API Default values and remove kwargs (3D)

- README.md
- requirements_optional_cuda.txt
- setup.py
Small modifications of the readme to make it more coherent with pip + improving the setup.py with more attributes to setup_tools (e.g. python_requires) and removing the support of "Windows" and python<3.6
Close #242
> MAINT improved installation instructions

- kymatio/scattering2d/scattering2d.py
- kymatio/scattering2d/tests/test_scattering2d.py
Done the change. The current state of the PR should fail on travis because tests don't reflect change
> API Change coeff order

- kymatio/scattering1d/scattering1d.py
- kymatio/scattering1d/tests/test_scattering1d.py
> API Change coefficient order

- README.md
Replace with `KYMATIO_BACKEND`.
> FIX Remove `KYMATIO_BACKEND_2D`

- README.md
small aesthetic/cosmetic changes to readme
> DOC readme fixes

- examples/3d/compute_speed.py
> FIX Make 3D benchmark run again

- .travis.yml
> TST Fix coverage reporting

- kymatio/scattering1d/backend/backend_skcuda.py
- kymatio/scattering1d/backend/backend_torch.py
Fixes some small issues (#296, #297) for the 1D backends.
> FIX+ENH Fix 1D backends

- README.md
- doc/source/installation.rst
- doc/source/userguide.rst
- kymatio/scattering2d/scattering2d.py
Various fixes: backend discussions, benchmarks, source installation instructions, and smaller stuff.
> DOC Fix documentation and README

- CONTRIBUTORS.md
- examples/3d/scattering3d_qm7.py
> FIX+DOC Typos in `scattering3d_qm7.py`

- doc/source/userguide.rst
Things that bugged me while reading the user guide. (No need to add me to the contributors list for that...)
> Minor proofreading of user guide

- CONTRIBUTORS.md
- kymatio/scattering2d/filter_bank.py
> FIX Remove unused import

- kymatio/scattering2d/filter_bank.py
> Avoid creating unneeded 2D Psi filters

- README.md
- doc/source/index.rst
> ENH Gihub logos

- kymatio/scattering2d/filter_bank.py
> ENH remove unusused fftshift option from filter banks

- kymatio/scattering2d/backend/backend_torch.py
Efforts to improve the 2D torch backend go here.
> ENH Optimize 2D torch modulus

- benchmarks/bench_backend_2d.py
Lets us benchmark the performance of the backends by measuring their throughput.
> ENH+WIP Add backend benchmarks

- kymatio/scattering2d/tests/test_scattering2d.py
> TST Test raised errors in `Scattering2D.forward`

- kymatio/scattering2d/backend/backend_skcuda.py
- kymatio/scattering2d/backend/backend_torch.py
- kymatio/scattering2d/filter_bank.py
- kymatio/scattering2d/tests/test_scattering2d.py
The Morlet/Gabor filterbank in Scattering2D is actually real-valued when expressed in the spectral domain. We can exploit this in the computation. (Possibly needs a test to make sure all code paths in cdgmm are covered.)
> ENH Use real filterbank in Scattering2D

- kymatio/scattering2d/backend/backend_skcuda.py
- kymatio/scattering2d/backend/backend_torch.py
- kymatio/scattering2d/filter_bank.py
- kymatio/scattering2d/scattering2d.py
> ENH Torch backend isn't necessary for creating filters

- Jenkinsfile
- tools/Dockerfile
Along with some other cleanups and efficiency improvements to test framework.
> FIX (merge?) Updates for new jenkins server

- kymatio/scattering2d/backend/backend_skcuda.py
- kymatio/scattering2d/backend/backend_torch.py
Closes #357  
This PR ensures that 2 cuda tensors are on the same GPU.
> FIX(merge?) different devices message error for 2D scattering

- kymatio/scattering2d/filter_bank.py
- kymatio/scattering2d/tests/test_scattering2d.py
> ENH(merge?) support of J=1 for 2D

- kymatio/scattering2d/tests/test_scattering2d.py
> ENH (merge?) adding more test for code coveraging purpose

- kymatio/scattering2d/scattering2d.py
- kymatio/scattering2d/tests/test_scattering2d.py
The objective of this PR is to clearly separate the primitive used by a torch modules in order to prepare an integration nn.functional/nn.module-like
> ENH(merge?) adding function .to() for 2D

- kymatio/scattering1d/scattering1d.py
- kymatio/scattering1d/utils.py
This PR does the same modifications from the 2D code ( #384 ).
> ENH adding to() and _apply to the 1D code

- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/scattering1d.py
Removed `import torch` from filter banks for 1D.
> ENH(merge?) removing torch from filter banks generation (1D)

- kymatio/scattering2d/backend/backend_skcuda.py
- kymatio/scattering2d/backend/backend_torch.py
- kymatio/scattering2d/scattering2d.py
- kymatio/scattering2d/tests/test_scattering2d.py
- kymatio/scattering2d/utils.py
> FIX BUG(merge?) J=ceil(log(N)/log(2))

- kymatio/scattering3d/filter_bank.py
- kymatio/scattering3d/scattering3d.py
- kymatio/scattering3d/tests/test_scattering3d.py
- kymatio/scattering3d/utils.py
This PR does the same modifications from the 2D code ( #384 ), and also remove torch from the filter bank building procedure
Close #351
Close #348
> ENH(merge?) adding to() and _apply to the 3D code 

- doc/source/developerguide.rst
> DOC Clean up developer's guide

- README.md
- doc/Makefile
- doc/source/codereference.rst
- doc/source/conf.py
- doc/source/developerguide.rst
- doc/source/index.rst
- doc/source/installation.rst
- doc/source/quickstart.rst
- doc/source/userguide.rst
As discussed in #432 , it's better to split the pull request into smaller pull request. This pull request changes the documentation in anticipation of 0.2.0. 
Questions: should the readme be included in this pull request or some other separate one? 
Do we want to create a new branch that is just a copy of master, merge all 0.2.0 changes into that one, then merge into master?
Also see #441 .
Recommended to be merged 1st.
> DOC Kymatio documentation 0.2.0 [1]

- Jenkinsfile
- tools/Dockerfile
- tools/travis_install.sh
To prepare for TF support, we update the Docker image and the Travis installation instructions. We also update the PyTorch installation commands.
> TST Update Travis and Jenkins for TF

- kymatio/frontend/tensorflow_frontend.py
- kymatio/scattering2d/backend/tensorflow_backend.py
- kymatio/scattering2d/frontend/tensorflow_frontend.py
- kymatio/scattering2d/tests/test_tensorflow_scattering2d.py
This is the PR for the 2d Tensorflow back/front ends.  This is up for review after NumPy is done. 
Unfortunately, squeeze is not an attribute on tensorflow tensors, so the biggest barrier currently is removing the usage of squeeze from core/scattering2d.
> ENH TensorFlow 2D Back/Frontend [3c]

- README.md
> update README, announce v0.2.a0 [ci skip]

- kymatio/__init__.py
> ENH Fix warning

- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/tests/test_numpy_scattering1d.py
Closes #497 
The other PR (#499) was too messy due to rebases and history conflicts, so I cherry-picked the top three commits onto 0.2.X and made this PR instead. If anything's missing, @edouardoyallon, let me know.
> 1D NumPy frontend

- kymatio/frontend/__init__.py
- kymatio/numpy.py
- kymatio/scattering1d/frontend/__init__.py
- kymatio/scattering2d/frontend/__init__.py
- kymatio/tensorflow.py
- kymatio/torch.py
> ENH remove duplication of ScatteringND classes

- kymatio/scattering3d/frontend/torch_frontend.py
- kymatio/scattering3d/tests/test_torch_scattering3d.py
> ENH Make 3D torch frontend batch shape agnostic

- benchmarks/benchmarks/bench_scattering1d.py
- benchmarks/benchmarks/bench_scattering2d.py
- benchmarks/benchmarks/bench_scattering3d.py
- benchmarks/benchmarks/common.py
> unify benchmarks

- examples/2d/plot_mnist_classify_torch.py
- kymatio/backend/base_backend.py
- kymatio/backend/numpy_backend.py
- kymatio/backend/tensorflow_backend.py
- kymatio/backend/torch_backend.py
- kymatio/backend/torch_skcuda_backend.py
- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- kymatio/scattering1d/backend/torch_skcuda_backend.py
- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/filter_bank.py
- kymatio/scattering1d/frontend/torch_frontend.py
- kymatio/scattering1d/tests/test_torch_scattering1d.py
- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/backend/tensorflow_backend.py
- kymatio/scattering2d/backend/torch_backend.py
- kymatio/scattering2d/backend/torch_skcuda_backend.py
- kymatio/scattering2d/filter_bank.py
- kymatio/scattering2d/tests/test_numpy_scattering2d.py
- kymatio/scattering2d/tests/test_tensorflow_scattering2d.py
- kymatio/scattering2d/tests/test_torch_scattering2d.py
- kymatio/scattering3d/backend/torch_backend.py
- kymatio/scattering3d/backend/torch_skcuda_backend.py
- kymatio/tests/test_torch_backend.py
> REF New simplifications

- kymatio/scattering3d/backend/tensorflow_backend.py
- kymatio/scattering3d/frontend/tensorflow_frontend.py
- kymatio/scattering3d/tests/test_tensorflow_scattering3d.py
This PR implements the harmonic 3D scattering in TensorFlow. 
#418
> TensorFlow 3D

- examples/2d/plot_invert_scattering_torch.py
- examples/2d/plot_scattering_disk.py
> Absolute path name

- kymatio/backend/numpy_backend.py
- kymatio/backend/torch_backend.py
- kymatio/frontend/numpy_frontend.py
- kymatio/frontend/torch_frontend.py
- kymatio/scattering3d/frontend/numpy_frontend.py
- kymatio/scattering3d/frontend/tensorflow_frontend.py
- kymatio/scattering3d/frontend/torch_frontend.py
> MAINT Adding contiguous tests

- examples/2d/plot_sklearn.py
- kymatio/sklearn.py
- kymatio/tests/test_sklearn.py
> ENH Add sklearn tranformer and example

- kymatio/scattering1d/tests/test_torch_scattering1d.py
> WIP Speed up test suite

- kymatio/frontend/entry.py
- kymatio/frontend/sklearn_frontend.py
- kymatio/scattering1d/frontend/sklearn_frontend.py
- kymatio/scattering1d/tests/test_utils_scattering1d.py
- kymatio/scattering2d/frontend/sklearn_frontend.py
- kymatio/scattering2d/tests/test_frontend_scattering2d.py
- kymatio/scattering3d/frontend/sklearn_frontend.py
- kymatio/sklearn.py
Also hooks sklearn in to the templated docs and fixes annoying error message (#561). See #562.
> REF+DOC Make sklearn importable from ScatteringEntry

- README.md
> fixing FI logo

- .circleci/config.yml
- examples/1d/plot_real_signal.py
> BUG website

- examples/3d/scattering3d_qm7_torch.py
I'd really appreciate if @eickenberg could have a very quick look to it. It's pretty basic.
Closes #111
> ENH very basic narrative

- README.md
- tests/scattering2d/test_keras_scattering2d.py
> fixing sklearn doc and transformers

- examples/2d/regularized_inverse_scattering_MNIST_torch.py
Addresses #542 and correct a bug to use this on a laptop.
> BUG in regularized inverse 2D

- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- kymatio/scattering2d/frontend/torch_frontend.py
- kymatio/scattering3d/frontend/numpy_frontend.py
- kymatio/scattering3d/frontend/torch_frontend.py
Remove some docs which are anyway overload by the new mechanism for documentation!
> ENH removing unused documentation thanks to the new doc mechanism

- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering2d/frontend/base_frontend.py
> ENH odcumentation of out_type

- kymatio/frontend/tensorflow_frontend.py
- kymatio/keras.py
- kymatio/scattering1d/frontend/keras_frontend.py
- kymatio/scattering1d/frontend/sklearn_frontend.py
- kymatio/scattering1d/utils.py
- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/backend/tensorflow_backend.py
- kymatio/scattering2d/backend/torch_skcuda_backend.py
- kymatio/scattering2d/frontend/keras_frontend.py
- kymatio/scattering2d/frontend/numpy_frontend.py
- kymatio/scattering2d/frontend/sklearn_frontend.py
- kymatio/scattering2d/frontend/tensorflow_frontend.py
- kymatio/scattering2d/frontend/torch_frontend.py
- kymatio/scattering3d/backend/numpy_backend.py
- kymatio/scattering3d/frontend/sklearn_frontend.py
- kymatio/sklearn.py
Attempt to fix the import issues for circleci
> ENH Relative import

- doc/source/codereference.rst
This fixes #583.
A little bit light on Torch and TF. Perhaps someone can fill in a bit? Otherwise let's just go with this.
> DOC Update code reference

- README.md
- doc/source/codereference.rst
- doc/source/userguide.rst
> DOC Fix discussions of frontends

- doc/source/userguide.rst
Are there other places where I need to add text about 3D scattering?
> DOC add userguide description of 3d scattering

- kymatio/scattering3d/frontend/base_frontend.py
> DOC Fix missing blank line in 3D doc example

- .circleci/config.yml
Hopefully fixes #600. Would probably have to merge into dev to see if it works.
> TST Install TF in Circle CI config

- .circleci/config.yml
Is it because there is no gpu?
> test circle ci

- .circleci/config.yml
- kymatio/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering3d/frontend/base_frontend.py
> FIX for v2 (the end)

- README.md
This Pull Request updates our README with the paper submitted to JMLR. 
This closes #610
> MAINT update readme with paper

- setup.py
> Fix setup style issues

- kymatio/backend/numpy_backend.py
- kymatio/backend/tensorflow_backend.py
- kymatio/backend/torch_backend.py
- kymatio/backend/torch_skcuda_backend.py
- kymatio/scattering3d/backend/tensorflow_backend.py
- kymatio/scattering3d/backend/torch_skcuda_backend.py
- tests/scattering2d/test_numpy_scattering2d.py
- tests/scattering2d/test_tensorflow_scattering2d.py
- tests/scattering2d/test_torch_scattering2d.py
- tests/scattering3d/test_torch_scattering3d.py
This PR removes the inplace argument. 
We should squash and merge the R2C pr soon! #573
> MAINT Inplace argument removal

- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- kymatio/scattering1d/backend/torch_skcuda_backend.py
- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/backend/tensorflow_backend.py
- kymatio/scattering2d/backend/torch_backend.py
- kymatio/scattering2d/backend/torch_skcuda_backend.py
- kymatio/scattering2d/core/scattering2d.py
- kymatio/scattering2d/filter_bank.py
- kymatio/scattering3d/core/scattering3d.py
- kymatio/scattering3d/filter_bank.py
- kymatio/scattering3d/frontend/tensorflow_frontend.py
- kymatio/scattering3d/frontend/torch_frontend.py
- kymatio/scattering3d/utils.py
This PR removes all Author headings.
> STY Remove Authors

- Jenkinsfile
While SCC is investigating the feasability of upgrading the GPUs, we
only have access to the one.
> TST Temporarily set number of GPUs to one

- examples/2d/plot_invert_scattering_torch.py
- examples/2d/plot_scattering_disk.py
Fix #594 
(more iterations / small issue with gray scale)
> [FIX] fixing colors

- .circleci/config.yml
This may not run unless we merge. Let's see.
> TST Try to get Circle CI working again

- kymatio/scattering2d/frontend/torch_frontend.py
This is a fix for multi-GPU scattering issues as previously raised. It was tested on torch 1.7, cuda 10.2 and 11.0
> Fix for multi-GPU scattering

- .circleci/config.yml
- .github/workflows/conda.yml
- .github/workflows/cuda.yml
- .github/workflows/pip.yml
- tools/Dockerfile
Modify circle ci and gh actions such that it works only with 1.7
> FIX 17 support for tests

- .github/workflows/conda.yml
- .github/workflows/cuda.yml
- .github/workflows/pip.yml
- Jenkinsfile
- README.md
- tests/scattering1d/test_torch_scattering1d.py
- tests/scattering2d/test_tensorflow_scattering2d.py
- tests/scattering2d/test_torch_scattering2d.py
- tests/scattering3d/test_torch_scattering3d.py
> TST Fix GHA issues

- kymatio/scattering1d/frontend/keras_frontend.py
- kymatio/scattering2d/frontend/keras_frontend.py
- tests/scattering2d/test_keras_scattering2d.py
fixes #637 
a v2 of #659 with a ton of help from @edouardoyallon :)
> implement get_config in 1d and 2d

- examples/2d/plot_filters.py
- kymatio/backend/numpy_backend.py
- kymatio/scattering1d/filter_bank.py
- kymatio/scattering2d/filter_bank.py
- kymatio/scattering2d/utils.py
- tests/scattering1d/test_numpy_backend_1d.py
[Reopened](https://github.com/kymatio/kymatio/pull/702). -- `.fft` is more performant per my benchmarks, and scipy [recommends against](https://docs.scipy.org/doc/scipy/reference/fftpack.html) `.fftpack`. As used throughout kymatio, it's just a drop-in replacement.
> `scipy.fftpack` -> `scipy.fft`

- kymatio/version.py
Version bump on master to align with what has been pushed to pypi.
> MAINT bump version

- README.md
@janden @rastegah 
This is a pull request for upating the README.md and thereaby the [kymat.io](https://www.kymat.io/) website about the Kymatio'22 workshop. 
@rastegah please lemme know if the readme is your liking.
> Mention Kymatio'22 workshop on README.md

- README.md
Thanks to @lostanlen for taking on the responsibilities of conference chair, and thanks to all the other organizers for their time and work @aliceCohenHadria, @vanessagd.2395, @lylyhan, @changhongw, @rastegah, and @janden. 
Can't wait for the next one! 
(in montreal maybe ;) ? )
> [REV] Removed mention of the 2022 conference from the README.md. 

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
`CONTRIBUTING.MD` has been updated with guidelines on making feature requests and bug fixes
* It explicitly outlines that an issue or feature request should be submitted before a PR
* The community will discuss the feature request and its roadmap
* Features for a PR should be planned to be small and manageable
> DOC updated contributing guidelines

- kymatio/scattering1d/filter_bank.py
> document `N` and `J` in `scattering_filter_factory`

- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/frontend/jax_frontend.py
- kymatio/scattering1d/frontend/keras_frontend.py
- kymatio/scattering1d/frontend/numpy_frontend.py
- kymatio/scattering1d/frontend/tensorflow_frontend.py
- kymatio/scattering1d/frontend/torch_frontend.py
- tests/scattering1d/test_correctness.py
closes #917
should be merged to both main branch and the v0.3 branch
tagging @eickenberg
> FIX set `average=None` in Scattering1D frontends

- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- tests/scattering1d/test_numpy_backend_1d.py
- tests/scattering1d/test_tensorflow_backend_1d.py
- tests/scattering1d/test_torch_backend_1d.py
for JTFS (the frequential scattering part, specifically)
tests included
> ENH 1d zero padding and complex FFT

- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- tests/scattering1d/test_numpy_backend_1d.py
- tests/scattering1d/test_tensorflow_backend_1d.py
- tests/scattering1d/test_torch_backend_1d.py
For JTFS
Initially authored by @cyrusvahidi and @MuawizChaudhary back in May (#808)
big thanks to y'all
> ENH JTFS `swap_time_frequency`

- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering1d/utils.py
- tests/scattering1d/test_keras_scattering1d.py
- tests/scattering1d/test_numpy_scattering1d.py
- tests/scattering1d/test_tensorflow_scattering1d.py
- tests/scattering1d/test_timefrequency_scattering.py
- tests/scattering1d/test_torch_scattering1d.py
- tests/scattering1d/test_utils_scattering1d.py
segue of #927 
it's not much, but it's something
`__init__` and `build` for `TimeFrequencyScatteringBase`
tests included
> ENH JTFS `__init__` and `build`

- tests/scattering1d/test_numpy_backend_1d.py
fix the failing test on one of the Kymatio Conda CI after #926 merge
https://github.com/kymatio/kymatio/runs/7846214378?check_suite_focus=true
> TST lower atol in NP cfft

- kymatio/scattering1d/backend/numpy_backend.py
- kymatio/scattering1d/backend/tensorflow_backend.py
- kymatio/scattering1d/backend/torch_backend.py
- tests/scattering1d/test_numpy_backend_1d.py
- tests/scattering1d/test_tensorflow_backend_1d.py
- tests/scattering1d/test_torch_backend_1d.py
The JTFS torch frontend requires a (very) special case for frequential padding so i made a small Kymatio 1D primitive for it. See docstring
Tests included
> ENH JTFS `pad_frequency`

- kymatio/scattering1d/core/scattering1d.py
- kymatio/scattering1d/core/timefrequency_scattering.py
- tests/scattering1d/test_timefrequency_scattering.py
A small PR which implements the mapping `U2 -> S2` in JTFS.
Tests and documentation are included
> ENH JTFS `time_averaging`

- kymatio/scattering1d/frontend/base_frontend.py
- tests/scattering1d/test_timefrequency_scattering.py
- tests/scattering1d/test_torch_scattering1d.py
> ENH JTFS `self.format` and `_check_runtime_args`

- README.md
Add version number, mentions of Jax, fix minor formatting.
> DOC Update README

- README.md
Looks like no one has read through this thing in several years…
> DOC More readme fixes

- README.md
- doc/Makefile
- doc/source/_static/custom.css
- doc/source/conf.py
- doc/source/sphinx_issues.py
- doc/source/whats_new.rst
- doc/source/whats_new/_preamble.rst
- doc/source/whats_new/v0.3.rst
Extracted the relevant bits from the sklearn sphinx setup. Also did some minor reformatting. Result looks like this:
> DOC Fix sphinx changelog

- .github/workflows/docs.yml
Make it manual dispatch and remove branch constraint. Also rename.
> MAINT Update docs workflow

- kymatio/version.py
Per @lostanlen's suggestion, we should be following PEP 440 here.
> MAINT Change current version to 0.4.0.dev0

- kymatio/jax.py
- kymatio/keras.py
- kymatio/numpy.py
- kymatio/sklearn.py
- kymatio/tensorflow.py
- kymatio/torch.py
Fixes #966 
+ coding style normalization (based on `black`)
> MAINT export `TimeFrequencyScattering` in all frontends

- kymatio/jax.py
JTFS Jax frontend is not yet implemented and tested.
I've removed the module export and will not reintroduce it until the frontend passes tests
> remove JTFS jax export 

- README.md
(master -> main)
95% test coverage now 💚
> renew badges on README

- kymatio/backend/numpy_backend.py
- kymatio/backend/tensorflow_backend.py
- kymatio/backend/torch_backend.py
- kymatio/scattering1d/core/timefrequency_scattering.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering2d/backend/numpy_backend.py
- kymatio/scattering2d/backend/torch_backend.py
- kymatio/scattering2d/core/scattering2d.py
- kymatio/scattering3d/backend/numpy_backend.py
- kymatio/scattering3d/backend/tensorflow_backend.py
- kymatio/scattering3d/backend/torch_backend.py
- kymatio/scattering3d/core/scattering3d.py
- tests/scattering1d/test_timefrequency_scattering.py
- tests/scattering2d/test_numpy_backend_2d.py
- tests/scattering2d/test_tensorflow_backend_2d.py
- tests/scattering2d/test_torch_backend_2d.py
fixes #942 
quoting @eickenberg 
> As long as this improves compatibility with the keywords used in other packages, which as far as I understand it does, I think this change should be made.
> MAINT concatenate --> stack

- AUTHORS.md
Shout out to @lylyhan @f0k @dylex @cyrusvahidi @changhongw @pawarrick 🙏🏻
> MAINT add 6 authors in `AUTHORS.md`

- kymatio/scattering1d/frontend/entry.py
- kymatio/scattering1d/frontend/jax_frontend.py
- tests/scattering1d/test_timefrequency_scattering.py
i've added the JAX frontend for JTFS
minimal tests on the frontend side
[EDIT by @lostanlen: fixes #1002]
> ENH JAX frontend for JTFS

- .github/workflows/docs.yml
> TST Modify docs workflow to upload artifact

- tools/Dockerfile
Fixes Jenkins failure due to #1028.
> TST Pin torch to 2.0

- .github/workflows/pip.yml
> TST Pin Jax to 0.4.19

- .github/workflows/conda.yml
- .github/workflows/pip.yml
- README.md
- setup.py
> TST Drop py37 from CI

- doc/source/index.rst
- kymatio/frontend/sklearn_frontend.py
- kymatio/frontend/tensorflow_frontend.py
- kymatio/frontend/torch_frontend.py
- kymatio/scattering1d/frontend/base_frontend.py
- kymatio/scattering2d/frontend/base_frontend.py
- kymatio/scattering3d/frontend/base_frontend.py
Fixes some issues with docstrings that have cropped up due to API updates and Sphinx version drift.
> DOC Fix docstrings

- .github/workflows/conda.yml
- .github/workflows/pip.yml
- README.md
Also fix README and update GHA workflow to use recent versions of actions.
> TST Test Torch v1.10 as well

- examples/2d/cifar_small_sample.py
This reverts commit 70c4f1cbf414f8eaed64e65ae8621c44567d41fa.
> Revert "Revert "FIX Update cifar_small_sample.py" (#1046)"
